# Generated by Django 5.2.11 on 2026-02-11 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelstation',
            options={'ordering': ['name'], 'verbose_name': 'Fuel Station', 'verbose_name_plural': 'Fuel Stations'},
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='retail_price',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=10),
        ),
    ]
